"""Ajout de date_reservation

Revision ID: 0fa29cb9cf74
Revises: 14abe7ff8f9c
Create Date: 2025-06-10 21:28:34.403267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa29cb9cf74'
down_revision = '14abe7ff8f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_reservation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking1', schema=None) as batch_op:
        batch_op.drop_column('date_reservation')

    # ### end Alembic commands ###
